<?php

/**
 * @license LGPLv3, https://opensource.org/licenses/LGPL-3.0
 * @copyright Aimeos (aimeos.org), 2026
 * @package MShop
 * @subpackage Feed
 */


namespace Aimeos\MShop\Feed\Manager\Lists;


/**
 * Default feed list manager for creating and handling feed list items.
 *
 * @package MShop
 * @subpackage Feed
 */
class Standard
	extends \Aimeos\MShop\Common\Manager\Lists\Base
	implements \Aimeos\MShop\Feed\Manager\Lists\Iface
{
	/** mshop/feed/manager/lists/submanagers
	 * List of manager names that can be instantiated by the feed list manager
	 *
	 * @param array List of sub-manager names
	 * @since 2026.01
	 */

	/** mshop/feed/manager/lists/name
	 * Class name of the used feed list manager implementation
	 *
	 * @param string Last part of the class name
	 * @since 2026.01
	 */

	/** mshop/feed/manager/lists/decorators/excludes
	 * Excludes decorators added by the "common" option from the feed list manager
	 *
	 * @param array List of decorator names
	 * @since 2026.01
	 * @see mshop/common/manager/decorators/default
	 * @see mshop/feed/manager/lists/decorators/global
	 * @see mshop/feed/manager/lists/decorators/local
	 */

	/** mshop/feed/manager/lists/decorators/global
	 * Adds a list of globally available decorators only to the feed list manager
	 *
	 * @param array List of decorator names
	 * @since 2026.01
	 * @see mshop/common/manager/decorators/default
	 * @see mshop/feed/manager/lists/decorators/excludes
	 * @see mshop/feed/manager/lists/decorators/local
	 */

	/** mshop/feed/manager/lists/decorators/local
	 * Adds a list of local decorators only to the feed list manager
	 *
	 * @param array List of decorator names
	 * @since 2026.01
	 * @see mshop/common/manager/decorators/default
	 * @see mshop/feed/manager/lists/decorators/excludes
	 * @see mshop/feed/manager/lists/decorators/global
	 */

	/** mshop/feed/manager/lists/insert/ansi
	 * Inserts a new feed list record into the database table
	 *
	 * @param string SQL statement for inserting records
	 * @since 2026.01
	 * @see mshop/feed/manager/lists/update/ansi
	 * @see mshop/feed/manager/lists/newid/ansi
	 * @see mshop/feed/manager/lists/delete/ansi
	 * @see mshop/feed/manager/lists/search/ansi
	 * @see mshop/feed/manager/lists/count/ansi
	 */

	/** mshop/feed/manager/lists/update/ansi
	 * Updates an existing feed list record in the database
	 *
	 * @param string SQL statement for updating records
	 * @since 2026.01
	 * @see mshop/feed/manager/lists/insert/ansi
	 * @see mshop/feed/manager/lists/newid/ansi
	 * @see mshop/feed/manager/lists/delete/ansi
	 * @see mshop/feed/manager/lists/search/ansi
	 * @see mshop/feed/manager/lists/count/ansi
	 */

	/** mshop/feed/manager/lists/newid/ansi
	 * Retrieves the ID generated by the database when inserting a new record
	 *
	 * @param string SQL statement for retrieving the last inserted record ID
	 * @since 2026.01
	 * @see mshop/feed/manager/lists/insert/ansi
	 * @see mshop/feed/manager/lists/update/ansi
	 * @see mshop/feed/manager/lists/delete/ansi
	 * @see mshop/feed/manager/lists/search/ansi
	 * @see mshop/feed/manager/lists/count/ansi
	 */

	/** mshop/feed/manager/lists/delete/ansi
	 * Deletes the items matched by the given IDs from the database
	 *
	 * @param string SQL statement for deleting items
	 * @since 2026.01
	 * @see mshop/feed/manager/lists/insert/ansi
	 * @see mshop/feed/manager/lists/update/ansi
	 * @see mshop/feed/manager/lists/newid/ansi
	 * @see mshop/feed/manager/lists/search/ansi
	 * @see mshop/feed/manager/lists/count/ansi
	 */

	/** mshop/feed/manager/lists/search/ansi
	 * Retrieves the records matched by the given criteria in the database
	 *
	 * @param string SQL statement for searching items
	 * @since 2026.01
	 * @see mshop/feed/manager/lists/insert/ansi
	 * @see mshop/feed/manager/lists/update/ansi
	 * @see mshop/feed/manager/lists/newid/ansi
	 * @see mshop/feed/manager/lists/delete/ansi
	 * @see mshop/feed/manager/lists/count/ansi
	 */

	/** mshop/feed/manager/lists/count/ansi
	 * Counts the number of records matched by the given criteria in the database
	 *
	 * @param string SQL statement for counting items
	 * @since 2026.01
	 * @see mshop/feed/manager/lists/insert/ansi
	 * @see mshop/feed/manager/lists/update/ansi
	 * @see mshop/feed/manager/lists/newid/ansi
	 * @see mshop/feed/manager/lists/delete/ansi
	 * @see mshop/feed/manager/lists/search/ansi
	 */
}
